"use client"

import { UserAdapter } from "@/adapters/UserAdapter";
import HomeHero from "@/components/home/ui/HomeHero";
import Specialties from "@/components/home/ui/Specialties";
import TopDoctors from "@/components/home/ui/TopDoctors";
// import { Metadata } from "next";
import { useEffect } from "react";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function Home() {
  useEffect(() => {
    
    const fetchUserProfile = async () => {
      const params = localStorage.getItem("auth_id"); 
      const profile = await UserAdapter.getUserProfile(params);
      const userProfileString = JSON.stringify(profile?.user);
      localStorage.setItem('userProfile', userProfileString);
    };
  
    fetchUserProfile();
  }, []);
  return (
    <div className="p-6">
      <HomeHero/>
      <Specialties/>
      <TopDoctors/>
    </div>
  );
}
